---
- hosts: localhost
  connection: local


  tasks: 
  - name: Debug Hello World
    debug: 
      msg: "Hello World"

  - name: Debug Source Vars if available
    debug: 
      msg: "something else"
    when: '"debug_source_vars" is defined'
